# Generated by Django 6.0.3 on 2026-04-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
